tap "homebrew/cask-versions"

brew "assh"
brew "curl"
brew "docker"
brew "htop"
brew "iproute2mac"
brew "neovim"
brew "python"
brew "zsh"
brew "zsh-completions"

cask "discord-canary"
cask "google-chrome-dev"
cask "iterm2"
cask "macpass"
cask "slack"
cask "spotify"
cask "steam"
cask "thunderbird"
cask "tunnelblick"
cask "virtualbox"
